### ISSUE TITLE
App keeps crashing 

### ISSUE THREAD

**Issue by Aaronbroughton344** [exbin/bined-android#14]
Here's a breakdown of the crash from logfox 
FATAL EXCEPTION: main
Process: org.exbin.bined.editor.android, PID: 14050
java.lang.StringIndexOutOfBoundsException: length=18; regionStart=19; regionLength=-1
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:85)
	at org.exbin.bined.android.basic.DefaultCodeAreaCharAssessor.getPreviewCharacter(SourceFile:79)
	at org.exbin.bined.highlight.android.NonprintablesCodeAreaAssessor.getPositionTextColor(SourceFile:96)
	at org.exbin.bined.highlight.android.SearchCodeAreaColorAssessor.getPositionTextColor(SourceFile:132)
	at org.exbin.framework.bined.BinEdCodeAreaAssessor.getPositionTextColor(SourceFile:143)
	at org.exbin.bined.android.basic.DefaultCodeAreaPainter.paintRowText(SourceFile:960)
	at org.exbin.bined.android.basic.DefaultCodeAreaPainter.paintRows(SourceFile:709)
	at org.exbin.bined.android.basic.DefaultCodeAreaPainter.paintMainArea(SourceFile:629)
	at org.exbin.bined.android.basic.DefaultCodeAreaPainter$2.onDraw(SourceFile:190)
	at android.view.View.draw(View.java:25177)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:1882)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at android.view.View.updateDisplayListIfDirty(View.java:24022)
	at android.view.View.draw(View.java:24907)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
	at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1179)
	at android.view.View.draw(View.java:25180)
	at com.android.internal.policy.DecorView.draw(DecorView.java:1161)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6067)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5722)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4811)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3302)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11362)

If anyone has information on any it's doing this it would be appreciated. It's crashed about 5 times before it went into deep sleep
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by hajdam** [comment]
Hi, thanks for the report.
I was unable to reproduce this, but tried to add some mitigation into current development build if you want to try it:
https://bined.exbin.org/download/?f=bined-android-0.2.4-SNAPSHOT.apk

**Comment by Aaronbroughton344** [comment]
Right on ill give it a shot

**Comment by hajdam** [comment]
Closing as there was no further response.
